version: '2.1'
services:
  latest:
    image: "linshenqi/authy"
    ports:
      - "10001:10001"
    volumes:
      - /data/authy/conf:/etc/authy/conf
      - /data/authy/log:/etc/authy/log
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
    healthcheck:
      test: curl -f --silent --fail http://127.0.0.1:8082/rush/v1/healthz || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
