version: 2
jobs:
  build:
    branches:
      ignore: /.*/
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: build docker image
          command: |
            mkdir -p /go/src/github.com/linshenqi/authy && cd /go/src/github.com/linshenqi/authy
            cp -r /home/circleci/project/* ./
            ls -al ./
            CGO_ENABLED=0 go build -o ./build/authy ./src/main.go
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            sh ./build_docker.sh
