
log:
  file: STDOUT
  level: DEBUG
  max_age: 1000h
  rotate: 24h

http:
  addr: :10001

wechat:
  endpoints:
    ashibro_dev:
      app_id: 1
      app_secret: 1

alipay:
  endpoints:
    ashibro:
      app_id: 1
      app_secret: 1
      public_key: pub

jwt:
  expiry: 0s

totp:
  endpoints:
    sms:
      issuer: i1
      code_len: 4
      expiry: 60s
    email:
      issuer: i1
      code_len: 6
      expiry: 10m