
http:
  addr: :9090

wechat:
  enable: true
  appid: wx919dfd3bc27aca6b
  appsecret: 4c2516457b0b6fffabf9623f97dbb490
  timeout: 8
  push_interval: 1
  max_retry: 3
  headers:
    Content-Type: application/json
