
log:
  file: STDOUT
  level: DEBUG
  max_age: 2160h
  rotate: 24h

http:
  addr: :10001

oauth:
  endpoints:
    ashibro_wechat:
      provider: wechat_oauth
      app_id: 1
      app_secret: 1
    ashibro_alipay:
      provider: alipay_oauth
      app_id: 1
      app_secret: 1
      public_key: pub

jwt:
  expiry: 24h

totp:
  endpoints:
    sms:
      issuer: i1
      code_len: 4
      expiry: 60s
    email:
      issuer: i1
      code_len: 6
      expiry: 10m
