
log:
  file: STDOUT
  level: DEBUG
  max_age: 1000h
  rotate: 24h

http:
  addr: :10001

wechat:
  endpoints:
    ashibro_dev:
      app_id: wx919dfd3bc27aca6b
      app_secret: 4c2516457b0b6fffabf9623f97dbb490

jwt:
  expiry: 24h