
log:
  file: STDOUT
  level: DEBUG
  max_age: 2160h
  rotate: 24h

http:
  addr: :10001

oauth:
  endpoints:
    ashibro_wechat:
      provider: wechat
      appid: 1
      secret: 1
    ashibro_alipay:
      provider: alipay
      appid: 1
      secret: 1
      publicKey: pub

jwt:
  expiry: 24h

totp:
  endpoints:
    sms:
      issuer: i1
      len: 4
      expiry: 60s
    email:
      issuer: i1
      len: 6
      expiry: 10m
